package com.electrotrack.view;

import com.electrotrack.dao.ComponentDAO;
import com.electrotrack.model.Component;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        setLocationRelativeTo(null); 
        loadTableData();           
    }

    public void loadTableData() {
        ComponentDAO compDAO = new ComponentDAO();
        List<Component> items = compDAO.readAll();
        populateTable(items);
    }

    // Standard structural helper to map the data array list directly onto JTable model headers
    private void populateTable(List<Component> items) {
        String[] columnNames = {"ID", "Part Number", "Item Name", "Category", "Stock Level", "Supplier ID"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        for (Component c : items) {
            Object[] row = {
                c.getComponentId(),
                c.getPartNumber(),
                c.getName(),
                c.getCategory(),
                c.getQuantityInStock(),
                c.getSupplierId()
            };
            model.addRow(row);
        }
        tblComponents.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComponents = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        btnUpdateStock = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ELECTROTRACK INVENTORY MANAGEMENT WORKSPACE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search Part/Category:");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblComponents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblComponents);

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAddItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddItem.setText("Add New Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnUpdateStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateStock.setText("Update Stock");
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete Item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateStock)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnReset)
                    .addComponent(btnAddItem)
                    .addComponent(btnUpdateStock)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim();

    // If empty, just fallback and refresh the data
    if (keyword.isEmpty()) {
        loadTableData();
        return;
    }

    // Execute standard database keyword query filter
    com.electrotrack.dao.ComponentDAO compDAO = new com.electrotrack.dao.ComponentDAO();
    java.util.List<com.electrotrack.model.Component> filteredItems = compDAO.search(keyword);

    // Update the JTable grid display with results
    populateTable(filteredItems);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      txtSearch.setText(""); 
    loadTableData();       
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
      
AddComponentFrame addForm = new AddComponentFrame(this);
addForm.setVisible(true);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
       int selectedRow = tblComponents.getSelectedRow();
    
    // Safety check: ensure a selection index was captured
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please click and highlight a component from the table first.", "Selection Required", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Capture specific cell item metadata variables out of the matching grid row array
    int compId = Integer.parseInt(tblComponents.getValueAt(selectedRow, 0).toString());
    String partNum = tblComponents.getValueAt(selectedRow, 1).toString();
    String currentQtyStr = tblComponents.getValueAt(selectedRow, 4).toString();

    // Spawn an input dialog window prompting the worker for data modification entries
    String input = javax.swing.JOptionPane.showInputDialog(this, "Enter updated inventory stock level for " + partNum + ":", currentQtyStr);
    
    if (input == null) return; 

    try {
        int newQty = Integer.parseInt(input.trim());
        if (newQty < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Stock quantities cannot drop below a 0 baseline.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        ComponentDAO compDAO = new ComponentDAO();
        if (compDAO.updateQuantity(compId, newQty)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inventory quantity modified successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadTableData(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to modify database record state.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid whole numerical index digit value.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     int selectedRow = tblComponents.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please click and select an engineering component row to delete.", "Selection Required", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

   
    int compId = Integer.parseInt(tblComponents.getValueAt(selectedRow, 0).toString());
    String partNum = tblComponents.getValueAt(selectedRow, 1).toString();
    String itemName = tblComponents.getValueAt(selectedRow, 2).toString();

   
    int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you absolutely sure you want to permanently delete " + partNum + " (" + itemName + ")?\nThis action cannot be undone.", 
            "Confirm Destructive Deletion", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE);

    if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
        com.electrotrack.dao.ComponentDAO compDAO = new com.electrotrack.dao.ComponentDAO();
        if (compDAO.delete(compId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Item successfully purged from structural inventory tracking.", "Record Purged", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadTableData(); // Sync up the dashboard interface list row entries instantly
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error processing execution query. Relational foreign key data ties might apply.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComponents;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables


}
